!!python/object:onn_config.AppConfig
adc_bits: 6
adc_scale_input: true
batch_size: 128
config_file: null
conv_method: patch
dac_bits: 4
driver_distortion_data_path: ./data/driver_distortion_data.csv
driver_distortion_polyfit_order: 3
driver_distortion_strength: 0.0
eval_only: false
jtc_half_size: 8
jtc_separation: 0
jtc_total_field: 16
learning_rate: 0.001
mrm_phase_data_path: ./data/mrm_phase_data.csv
mrm_phase_distortion_strength: 0.0
mrm_phase_polyfit_order: 3
mrm_power_data_path: ./data/mrm_power_data.csv
mrm_power_distortion_strength: 0.0
mrm_power_polyfit_order: 3
num_epochs: 30
num_identical_layers: 7
output_dir: ./runs/my_exp
pd_tia_distortion_data_path: ./data/pd_tia_distortion_data.csv
pd_tia_distortion_polyfit_order: 3
pd_tia_distortion_strength: 0.0
pretrained_weights: ''
