adc_bits: 6
adc_scale_input: true
config_file: template.yaml
dac_bits: 4
driver_distortion_data_path: ./component_data/driver_sim_data.csv
driver_distortion_polyfit_order: 3
driver_distortion_strength: 0.0
jtc_half_size: 8
jtc_separation: 0
jtc_total_field: 16
mrm_phase_data_path: ./component_data/mrm_phase_sim_data.csv
mrm_phase_distortion_strength: 0.0
mrm_phase_polyfit_order: null
mrm_power_data_path: ./component_data/mrm_pwr_w_sim_data.csv
mrm_power_distortion_strength: 0.0
mrm_power_polyfit_order: null
output_dir: tempdir
pd_tia_distortion_data_path: ./component_data/pd_tia_sim_data.csv
pd_tia_distortion_polyfit_order: 3
pd_tia_distortion_strength: 0.0
num_identical_layers: 1
num_epochs: 20
learning_rate: 1e-3
batch_size: 32
eval_only: False
pretrained_weights: ""
run_pretrain_tests: True
