adc_bits: 6
scale_output: "none"
config_file: template.yaml
dac_bits: 4
driver_distortion_data_path: ./component_data/driver_sim_data.csv
driver_distortion_polyfit_order: 3
driver_distortion_strength: 1.0
jtc_half_size: 8
jtc_separation: 0
jtc_total_field: 16
mrm_phase_data_path: ./component_data/mrm_phase_sim_data.csv
mrm_phase_distortion_strength: 1.0
mrm_phase_polyfit_order: null
mrm_power_data_path: ./component_data/mrm_pwr_w_sim_data.csv
mrm_power_distortion_strength: 1.0
mrm_power_polyfit_order: null
output_dir: tempdir
pd_tia_distortion_data_path: ./component_data/pd_tia_sim_data.csv
pd_tia_distortion_polyfit_order: 2
pd_tia_distortion_strength: 1.0
pd_distortion_data_path: ./component_data/pd_sim_data.csv
pd_distortion_polyfit_order: null
pd_distortion_strength: 1.0
tia_distortion_data_path: ./component_data/tia_sim_data.csv
tia_distortion_polyfit_order: null
tia_distortion_strength: 1.0
ler_std_dev: 0.01
conv_backend: jtc_emulation
num_identical_layers: 1
num_epochs: 20
learning_rate: 0.001
batch_size: 128
eval_only: False
pretrained_weights: ""
run_pretrain_tests: True
loss: 0.96
