adc_bits: 6
batch_size: 128
config_file: configs/config_paper_vgg11_best.yaml
conv_backend: jtc_fast
conv_method: patch
dac_bits: 4
dataset: cifar10
driver_distortion_data_path: ./component_data/driver_sim_data.csv
driver_distortion_polyfit_order: null
driver_distortion_strength: 0.0
eval_only: false
fourier_plane_bits: null
input_length: 8
jtc_separation: 7
jtc_total_field: 32
kernel_length: 3
learning_rate: 0.01
ler_std_dev: 0.0
loss: 0.96
model_arch: ftvgg11
mrm_phase_data_path: ./component_data/mrm_phase_sim_data.csv
mrm_phase_distortion_strength: 0.0
mrm_phase_polyfit_order: null
mrm_power_data_path: ./component_data/mrm_pwr_w_sim_data.csv
mrm_power_distortion_strength: 0.0
mrm_power_polyfit_order: null
normalize_blocks: false
num_epochs: 10
num_identical_layers: 0
output_dir: runs/ftvgg11_cifar10_onehot_tia
output_length: null
pd_distortion_data_path: ./component_data/pd_sim_data.csv
pd_distortion_polyfit_order: null
pd_distortion_strength: 0.0
pd_tia_distortion_data_path: ./component_data/pd_tia_sim_data.csv
pd_tia_distortion_polyfit_order: null
pd_tia_distortion_strength: 0.0
pretrain_tests_only: false
pretrained_weights: ''
quantizer: ste_clipped
run_pretrain_tests: false
scale_output: none
tia_distortion_data_path: ./component_data/tia_sim_data.csv
tia_distortion_polyfit_order: null
tia_distortion_strength: 1.0
enable_compile: false
